pg:
  connstr: "postgres://postgres:postgres@postgres/postgres?sslmode=disable"
  maxconns: 30
  minconns: 5
  maxconnlifetime: 1800   # seconds
  maxconnidletime: 300

hasher:
  cost: 12

jwt:
  ttl: 15m

grpc:
  addr: ":50051"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

throttle:
  maxattempts: 10
  blockduration: 5m